/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawalsRouteImport } from './routes/withdrawals'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SenderRangeRouteImport } from './routes/sender-range'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as GetNumberRouteImport } from './routes/get-number'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as BulkAllocateRouteImport } from './routes/bulk-allocate'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as AccessListRouteImport } from './routes/access-list'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin.withdrawals'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportRouteImport } from './routes/admin.report'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminOtpsRouteImport } from './routes/admin.otps'
import { Route as AdminNoticesRouteImport } from './routes/admin.notices'
import { Route as AdminGatewaysRouteImport } from './routes/admin.gateways'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAllocationsRouteImport } from './routes/admin.allocations'
import { Route as ApiInboxStreamRouteImport } from './routes/api/inbox/stream'
import { Route as ApiPublicCronCleanupInactiveRouteImport } from './routes/api/public/cron.cleanup-inactive'

const WithdrawalsRoute = WithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SenderRangeRoute = SenderRangeRouteImport.update({
  id: '/sender-range',
  path: '/sender-range',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const GetNumberRoute = GetNumberRouteImport.update({
  id: '/get-number',
  path: '/get-number',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkAllocateRoute = BulkAllocateRouteImport.update({
  id: '/bulk-allocate',
  path: '/bulk-allocate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessListRoute = AccessListRouteImport.update({
  id: '/access-list',
  path: '/access-list',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/admin/withdrawals',
  path: '/admin/withdrawals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportRoute = AdminReportRouteImport.update({
  id: '/admin/report',
  path: '/admin/report',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/admin/payouts',
  path: '/admin/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOtpsRoute = AdminOtpsRouteImport.update({
  id: '/admin/otps',
  path: '/admin/otps',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNoticesRoute = AdminNoticesRouteImport.update({
  id: '/admin/notices',
  path: '/admin/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGatewaysRoute = AdminGatewaysRouteImport.update({
  id: '/admin/gateways',
  path: '/admin/gateways',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAllocationsRoute = AdminAllocationsRouteImport.update({
  id: '/admin/allocations',
  path: '/admin/allocations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInboxStreamRoute = ApiInboxStreamRouteImport.update({
  id: '/api/inbox/stream',
  path: '/api/inbox/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronCleanupInactiveRoute =
  ApiPublicCronCleanupInactiveRouteImport.update({
    id: '/api/public/cron/cleanup-inactive',
    path: '/api/public/cron/cleanup-inactive',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-list': typeof AccessListRoute
  '/api-keys': typeof ApiKeysRoute
  '/bulk-allocate': typeof BulkAllocateRoute
  '/console': typeof ConsoleRoute
  '/get-number': typeof GetNumberRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/sender-range': typeof SenderRangeRoute
  '/signup': typeof SignupRoute
  '/summary': typeof SummaryRoute
  '/withdrawals': typeof WithdrawalsRoute
  '/admin/allocations': typeof AdminAllocationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/gateways': typeof AdminGatewaysRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/otps': typeof AdminOtpsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/report': typeof AdminReportRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/api/health': typeof ApiHealthRoute
  '/admin/': typeof AdminIndexRoute
  '/api/inbox/stream': typeof ApiInboxStreamRoute
  '/api/public/cron/cleanup-inactive': typeof ApiPublicCronCleanupInactiveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-list': typeof AccessListRoute
  '/api-keys': typeof ApiKeysRoute
  '/bulk-allocate': typeof BulkAllocateRoute
  '/console': typeof ConsoleRoute
  '/get-number': typeof GetNumberRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/sender-range': typeof SenderRangeRoute
  '/signup': typeof SignupRoute
  '/summary': typeof SummaryRoute
  '/withdrawals': typeof WithdrawalsRoute
  '/admin/allocations': typeof AdminAllocationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/gateways': typeof AdminGatewaysRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/otps': typeof AdminOtpsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/report': typeof AdminReportRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/api/health': typeof ApiHealthRoute
  '/admin': typeof AdminIndexRoute
  '/api/inbox/stream': typeof ApiInboxStreamRoute
  '/api/public/cron/cleanup-inactive': typeof ApiPublicCronCleanupInactiveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-list': typeof AccessListRoute
  '/api-keys': typeof ApiKeysRoute
  '/bulk-allocate': typeof BulkAllocateRoute
  '/console': typeof ConsoleRoute
  '/get-number': typeof GetNumberRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/sender-range': typeof SenderRangeRoute
  '/signup': typeof SignupRoute
  '/summary': typeof SummaryRoute
  '/withdrawals': typeof WithdrawalsRoute
  '/admin/allocations': typeof AdminAllocationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/gateways': typeof AdminGatewaysRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/otps': typeof AdminOtpsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/report': typeof AdminReportRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/api/health': typeof ApiHealthRoute
  '/admin/': typeof AdminIndexRoute
  '/api/inbox/stream': typeof ApiInboxStreamRoute
  '/api/public/cron/cleanup-inactive': typeof ApiPublicCronCleanupInactiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-list'
    | '/api-keys'
    | '/bulk-allocate'
    | '/console'
    | '/get-number'
    | '/inbox'
    | '/login'
    | '/profile'
    | '/sender-range'
    | '/signup'
    | '/summary'
    | '/withdrawals'
    | '/admin/allocations'
    | '/admin/audit'
    | '/admin/gateways'
    | '/admin/notices'
    | '/admin/otps'
    | '/admin/payouts'
    | '/admin/report'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/api/health'
    | '/admin/'
    | '/api/inbox/stream'
    | '/api/public/cron/cleanup-inactive'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-list'
    | '/api-keys'
    | '/bulk-allocate'
    | '/console'
    | '/get-number'
    | '/inbox'
    | '/login'
    | '/profile'
    | '/sender-range'
    | '/signup'
    | '/summary'
    | '/withdrawals'
    | '/admin/allocations'
    | '/admin/audit'
    | '/admin/gateways'
    | '/admin/notices'
    | '/admin/otps'
    | '/admin/payouts'
    | '/admin/report'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/api/health'
    | '/admin'
    | '/api/inbox/stream'
    | '/api/public/cron/cleanup-inactive'
  id:
    | '__root__'
    | '/'
    | '/access-list'
    | '/api-keys'
    | '/bulk-allocate'
    | '/console'
    | '/get-number'
    | '/inbox'
    | '/login'
    | '/profile'
    | '/sender-range'
    | '/signup'
    | '/summary'
    | '/withdrawals'
    | '/admin/allocations'
    | '/admin/audit'
    | '/admin/gateways'
    | '/admin/notices'
    | '/admin/otps'
    | '/admin/payouts'
    | '/admin/report'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/api/health'
    | '/admin/'
    | '/api/inbox/stream'
    | '/api/public/cron/cleanup-inactive'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessListRoute: typeof AccessListRoute
  ApiKeysRoute: typeof ApiKeysRoute
  BulkAllocateRoute: typeof BulkAllocateRoute
  ConsoleRoute: typeof ConsoleRoute
  GetNumberRoute: typeof GetNumberRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SenderRangeRoute: typeof SenderRangeRoute
  SignupRoute: typeof SignupRoute
  SummaryRoute: typeof SummaryRoute
  WithdrawalsRoute: typeof WithdrawalsRoute
  AdminAllocationsRoute: typeof AdminAllocationsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminGatewaysRoute: typeof AdminGatewaysRoute
  AdminNoticesRoute: typeof AdminNoticesRoute
  AdminOtpsRoute: typeof AdminOtpsRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminReportRoute: typeof AdminReportRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiInboxStreamRoute: typeof ApiInboxStreamRoute
  ApiPublicCronCleanupInactiveRoute: typeof ApiPublicCronCleanupInactiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdrawals': {
      id: '/withdrawals'
      path: '/withdrawals'
      fullPath: '/withdrawals'
      preLoaderRoute: typeof WithdrawalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sender-range': {
      id: '/sender-range'
      path: '/sender-range'
      fullPath: '/sender-range'
      preLoaderRoute: typeof SenderRangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-number': {
      id: '/get-number'
      path: '/get-number'
      fullPath: '/get-number'
      preLoaderRoute: typeof GetNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-allocate': {
      id: '/bulk-allocate'
      path: '/bulk-allocate'
      fullPath: '/bulk-allocate'
      preLoaderRoute: typeof BulkAllocateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-list': {
      id: '/access-list'
      path: '/access-list'
      fullPath: '/access-list'
      preLoaderRoute: typeof AccessListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/admin/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/report': {
      id: '/admin/report'
      path: '/admin/report'
      fullPath: '/admin/report'
      preLoaderRoute: typeof AdminReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/admin/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/otps': {
      id: '/admin/otps'
      path: '/admin/otps'
      fullPath: '/admin/otps'
      preLoaderRoute: typeof AdminOtpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notices': {
      id: '/admin/notices'
      path: '/admin/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AdminNoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gateways': {
      id: '/admin/gateways'
      path: '/admin/gateways'
      fullPath: '/admin/gateways'
      preLoaderRoute: typeof AdminGatewaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/allocations': {
      id: '/admin/allocations'
      path: '/admin/allocations'
      fullPath: '/admin/allocations'
      preLoaderRoute: typeof AdminAllocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inbox/stream': {
      id: '/api/inbox/stream'
      path: '/api/inbox/stream'
      fullPath: '/api/inbox/stream'
      preLoaderRoute: typeof ApiInboxStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/cleanup-inactive': {
      id: '/api/public/cron/cleanup-inactive'
      path: '/api/public/cron/cleanup-inactive'
      fullPath: '/api/public/cron/cleanup-inactive'
      preLoaderRoute: typeof ApiPublicCronCleanupInactiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessListRoute: AccessListRoute,
  ApiKeysRoute: ApiKeysRoute,
  BulkAllocateRoute: BulkAllocateRoute,
  ConsoleRoute: ConsoleRoute,
  GetNumberRoute: GetNumberRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SenderRangeRoute: SenderRangeRoute,
  SignupRoute: SignupRoute,
  SummaryRoute: SummaryRoute,
  WithdrawalsRoute: WithdrawalsRoute,
  AdminAllocationsRoute: AdminAllocationsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminGatewaysRoute: AdminGatewaysRoute,
  AdminNoticesRoute: AdminNoticesRoute,
  AdminOtpsRoute: AdminOtpsRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminReportRoute: AdminReportRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  ApiHealthRoute: ApiHealthRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiInboxStreamRoute: ApiInboxStreamRoute,
  ApiPublicCronCleanupInactiveRoute: ApiPublicCronCleanupInactiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
